#!/usr/bin/env python

"""Simple script to show dev params from dict"""


dev_name=input('Enter device name:')


london_co={
    'r1': {
        'location': '21 New globe walk',
        'vendor:':'Cisco',
        'model':'4451',
        'ios':'15.4',
        'ip':'10.255.0.1'
        },
    'r2': {
        'location': '21 New Globe Walk',
        'vendor': 'Cisco',
        'model': '4451',
        'ios': '15.4',
        'ip': '10.255.0.2'
        }
    }

print(london_co.setdefault(dev_name))

