#!/usr/bin/env python
# -*- coding: utf-8 -*-

""" Func takes 'access_mode_template',
    'access_config' and 'port_security_template'
    and returns access mode port list """

access_mode_template = [
    'switchport mode access', 'switchport access vlan {}',
    'switchport nonegotiate', 'spanning-tree portfast',
    'spanning-tree bpduguard enable'
]

access_config = {
    'FastEthernet0/12': 10,
    'FastEthernet0/14': 11,
    'FastEthernet0/16': 17
}

port_security_template = [
    'switchport port-security maximum 2',
    'switchport port-security violation restrict',
    'switchport port-security'
]


def generate_access_config(intf_vlan_mapping, access_template, psecurity=None, *arg):
    #take data from dict
    for intf, vlan in intf_vlan_mapping.items():
        #combine both list and dict + join list with dict values
        if psecurity==None:
            access_config = intf+('\n'.join(access_template).format(vlan))
            print(access_config)
        else:
            access_config = intf+('\n'.join(access_template+psecurity).format(vlan))
            print(access_config)
            
generate_access_config(access_config, access_mode_template, port_security_template)

